version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: messenger-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: messenger_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./messenger-app
    container_name: messenger-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: messenger_db
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    tty: true

volumes:
  mysql_data: